---
- name: MongoDB | Upload and unarchive backup dump
  unarchive:
    src: "{{ restore_file }}"
    dest: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}"

- name: MongoDB | Restore mongo admin database
  shell: "mongorestore -d {{ backup_mongodb_admin_db }} --username=\"{{ backup_mongodb_root_user }}\" --password=\"{{ backup_mongodb_root_pass }}\" {{ backup_mongodb_backup_file_name }}/admin"
  args:
    chdir: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}"

- name: MongoDB | Restore mongo database
  shell: "mongorestore -d {{ backup_mongodb_db }} --username=\"{{ backup_mongodb_user }}\" --password=\"{{ backup_mongodb_pass }}\" {{ backup_mongodb_backup_file_name }}/{{ backup_mongodb_db }}"
  args:
    chdir: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}"
